name: system tests

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make check
        run: make check

  macOS:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        #arch: ["ppc", "i386", "x86_64", "arm64", "arm" ]
        # XCode-12.4, can compile 'i386' (deprecated warning), 'x86_64', 'arm64' (but fails with SDK10.15's <stdio.h>) and 'arm' (same as 'arm64')
        arch: ["x86_64" ]
    env:
      arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: XCode version
        run: |
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || true
          xcodebuild -version || true
      - name: supported archs
        run: |
          mkdir -p .github/_testbuilds
          touch .github/_testbuilds/test.c
          cc -c .github/_testbuilds/test.c -o .github/_testbuilds/test.${arch}.o -arch ${arch}
      - name: build
        run: make CFLAGS="-arch ${arch}"

  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        #arch: ["x86", "amd64", "x64", "x86_64"]
        arch: ["amd64"]
          # '2010' and '90' yield "The system cannot find the path specified"
          # although that's most likely due to the Import-VisualStudioVars call
          #vs_ver: [2019, 2010, 90]
        vs_ver: [2019]
    env:
      ARCHITECTURE: ${{ matrix.arch }}
      VS_VER: ${{ matrix.vs_ver }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: pwsh
        run: |
            $ErrorActionPreference = 'continue'
            function exec
            {
                param ( [ScriptBlock] $ScriptBlock )
                & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
                if ($LastExitCode -ne 0) { exit $LastExitCode }
            }
            echo "ARCH_FLAGS = $env:ARCH_FLAGS"
            Import-PackageProvider NuGet -Force
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
            Install-Module Pscx -AllowClobber
            Install-Module VSSetup -Scope CurrentUser
            if($env:VS_VER -eq "2019")
            {
            }
            else
            {
                Import-VisualStudioVars -VisualStudioVersion $env:VS_VER -Architecture $env:ARCHITECTURE
            }
            nmake /f Makefile
      - name: Only Build
        shell: pwsh
        run: |
            nmake /f Makefile
