name: dynamic matrix

on: [push]

jobs:
  script1:
    runs-on: ubuntu-latest
    steps:
      - name: create script
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          echo "$MY_STRING"
          echo "$MY_STRING" > script.sh
      - name: show script
        run: cat script.sh

  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install curl jq
      - name: generate matrix
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(.github/utils/getdockerimages.sh)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run_matrix:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        series: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
      fail-fast: false
    container: buildpack-deps:${{ matrix.series }}

    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release
      - name: get distribution
        run: lsb_release -a
