name: coding standards

on: [push, pull_request]

jobs:
  illegally_executable_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ungit
        run: rm -rf .git
      - name: store variable
        run: |
          FOO=foo
          echo "FOO: ${FOO}"
          echo "BAR: ${BAR}"
          echo "FOO=fufu" >> $GITHUB_ENV
        env:
          BAR: bar
      - name: retrieve variables
        run: |
          echo "FOO: ${FOO}"
          echo "BAR: ${BAR}"
      - name: find executable files
        run: |
          if find . -type f -executable -iregex '.*\.\(pd\|txt\|h\|c[^.]*\|h[^.]*\)$' | grep .; then
            echo "EXECUTABLE FILES FOUND"
            throw "Some files are now executable but shouldn't be"
            exit 1
          fi

  check-whitespace:
    if: ${{ github.event_name == 'pull_request' && ( github.event.action == 'opened' || github.event.action == 'synchronize' ) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: git diff-index
      run: |
        git diff-index --check ${{github.event.pull_request.base.sha}}
