name: coding standards

on: [push, pull_request]

jobs:
  check_file_permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: find data files that are executable
        run: |
          if find $(git diff --name-only ${{github.event.pull_request.base.sha}} ) -type f -executable -iregex '.*\.\(pd\|txt\|h\|c[^.]*\|h[^.]*\)$' | grep .; then
            echo "Data files must never have the EXECUTABLE BIT set!"
            exit 2
          fi

  check-whitespace:
    if: ${{ github.event_name == 'pull_request' && ( github.event.action == 'opened' || github.event.action == 'synchronize' ) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: use 'git diff-index' to check for whitespace errors
      run: |
        git diff-index --check ${{github.event.pull_request.base.sha}}
