name: 2d action matrix

on: [push]

jobs:
  mjob:
    strategy:
      matrix:
        float: [32, 64]
        msystem: [mingw64, mingw32, clang64, clangarm64]
        include:
          # the extra 'ucrt64' msystem runs once (only!), but without a 'float'
          - msystem: ucrt64
            runner: windows-latest
          - msystem: mingw64
            runner: windows-latest
          - msystem: mingw32
            runner: windows-latest
          - msystem: clang64
            runner: windows-latest
          - msystem: clangarm64
            runner: windows-11-arm
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: false
      - name: Hello World
        run: |
          echo hello world
          echo "float  : ${{ matrix.float }}"
          echo "msystem: ${{ matrix.msystem }}"
          echo "runner : ${{ matrix.runner }}"
          uname
