name: 2d action matrix

on: [push]

jobs:
  mjob:
    strategy:
      matrix:
        float: [32, 64]
        # extra 'clang64' msystem
        msystem: [ucrt64, mingw64, mingw32, clang64]
        include:
          - msystem: ucrt64
            runner: windows-latest
          - msystem: mingw64
            runner: windows-latest
          - msystem: mingw32
            runner: windows-latest
          # extra 'clangarm64' msystem
          - msystem: clangarm64
            runner: windows-latest
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo hello world
          echo "float  : ${{ matrix.float }}"
          echo "msystem: ${{ matrix.msystem }}"
          echo "runner : ${{ matrix.runner }}"
