name: 2d action matrix

on: [push]

jobs:
  mjob:
    strategy:
      fail-fast: false
      matrix:
        float: [32, 64]
        msystem:
          - UCRT64
          - MINGW32
          - MINGW64
          - CLANG64
          - CLANGARM64
        include:
          # the extra 'msys' msystem runs once (only!), but without a 'float'
          - msystem: MSYS
            runner: windows-latest
          - msystem: UCRT64
            runner: windows-latest
          - msystem: MINGW64
            runner: windows-latest
          - msystem: MINGW32
            runner: windows-latest
          - msystem: CLANG64
            runner: windows-latest
          - msystem: CLANGARM64
            runner: windows-11-arm
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: true
          pacboy: >-
            toolchain:p
            base-devel:
      - name: Hello World
        run: |
          echo hello world
          echo "float  : ${{ matrix.float }}"
          echo "msystem: ${{ matrix.msystem }}"
          echo "runner : ${{ matrix.runner }}"
          uname -a || true
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          make || true
          file test*
          make check
