name: MSYS zipper

on: [push]

jobs:
  MsysZip:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          path-type: inherit
      - name: Checkout code
        uses: actions/checkout@v2
      - name: zip
        run: zip -r oopsie.zip oopsie
      - name: unzip
        run: unzip oopsie.zip -d zoopsie

  ASIOSDK:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          path-type: inherit
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ASIOSDK
        run: |
          wget -q -O asiosdk.zip https://www.steinberg.net/asiosdk
          unzip -q asiosdk.zip -d asio
          i=0; for f in asio/*/; do test -d "${f}" || break; echo "${f}"; until mv -v "${f%/}" asio/ASIOSDK; do echo "trying $i"; sleep 1; i=$((i+1)); if [ $i -ge 10 ]; then echo "giving up"; break; fi; done; done

