name: MSYS zipper

on: [push]

jobs:
  MsysZip:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          path-type: inherit
      - name: Checkout code
        uses: actions/checkout@v2
      - name: zip
        run: zip -r oopsie.zip oopsie
      - name: unzip
        run: unzip oopsie.zip -d zoopsie
